// wit/host.wit
package example:host;

//world host {
//  import print: func(msg: string);

//  export run: func();
//}

interface foo {
  hello: func(name: string) -> string;
}

interface bar {
  say: func(name: string);
}

world host {
  export foo;
  import bar;
}