[package]
name = "hermes"
description = "The Hermes Node"
keywords = ["cardano", "catalyst", "hermes"]
categories = ["command-line-utilities"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hermes"
path = "src/main.rs"

[lib]
name = "lib"
path = "src/lib.rs"
