[package]
name = "hermes"
description = "The Hermes Node"
license = "Apache-2.0"
repository = "https://github.com/input-output-hk/hermes"
keywords = ["cardano", "catalyst", "hermes"]
categories = ["command-line-utilities"]
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "hermes"
path = "src/main.rs"

[lib]
name = "lib"
path = "src/lib.rs"
